line-length = 120

[lint]
extend-select = ["ALL"]
ignore = [
    "T201",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D202",
    "D400",
    "D415",
]

